<?php

declare(strict_types=1);

namespace Domain\CognitiveGovernance;

/**
 * Registre officiel des injections cognitives runtime (PHP local, sans dépendances externes).
 * PromptBuilder reste assembleur : ce fichier décrit ce qui est autorisé, ordonné et auditable.
 *
 * @phpstan-type InjectionDef array{
 *   injection_key: string,
 *   label: string,
 *   category: string,
 *   priority: int,
 *   injection_order: int,
 *   max_chars: int|null,
 *   soft_budget: int|null,
 *   hard_budget: int|null,
 *   context_scope: string,
 *   cognitive_layer: string,
 *   provenance_required: bool,
 *   deterministic: bool,
 *   optional: bool,
 *   requires_expert_mode: bool,
 *   retrieval_allowed: bool,
 *   deduplication_key: string|null,
 *   pruning_priority: int,
 *   source_types: list<string>,
 *   supports_cross_context: bool,
 *   enabled_by_default: bool,
 *   channel: string,
 *   trace_block_id: string|null
 * }
 */
final class PromptInjectionRegistry
{
    public const SCHEMA_VERSION = '1.0.0';

    /** Ordre gouverné — prompt système (assemblage PromptBuilder::buildSystemContent et extensions). */
    public const OFFICIAL_ORDER_SYSTEM = [
        'global_system',
        'persona',
        'soul',
        'evidence_discipline',
        'argument_discipline',
        'playbook_discipline',
        'interaction_contract_system',
        'decision_dynamics',
        'social_dynamics_system',
        'context_document_system',
        'decision_memory_system',
        'repetition_reduction_system',
    ];

    /** Ordre gouverné — message utilisateur Decision Room (segments tracés aujourd’hui). */
    public const OFFICIAL_ORDER_DECISION_ROOM_USER = [
        'context_document',
        'session_objective',
        'strategic_context_guidance',
        'playbook_block',
        'playbook_debate_discipline',
        'session_history_rounds',
        'debate_argument_memory',
        'social_dynamics_policy',
        'social_dynamics_context',
        'agent_context_memory',
        'beliefs_prioritized',
        'beliefs_contested',
        'beliefs_fragile_assumptions',
        'beliefs_invalidated_optional',
        'round_instruction',
        'interaction_contract_user',
        'response_format_weighted',
        'forced_disagreement',
        'final_vote_instruction',
        'synthesizer_reliability_envelope',
        'synthesizer_output_format',
    ];

    /** block_id (trace MVP) → injection_key */
    public const BLOCK_ID_TO_INJECTION_KEY = [
        'context_document' => 'context_document',
        'objective' => 'session_objective',
        'strategic_context_guidance' => 'strategic_context_guidance',
        'playbook_block' => 'playbook_block',
        'debate_discipline' => 'playbook_debate_discipline',
        'previous_rounds' => 'session_history_rounds',
        'argument_memory' => 'debate_argument_memory',
        'social_policy' => 'social_dynamics_policy',
        'social_dynamics_block' => 'social_dynamics_context',
        'agent_context_memory' => 'agent_context_memory',
        'beliefs_prioritized' => 'beliefs_prioritized',
        'beliefs_contested' => 'beliefs_contested',
        'beliefs_fragile_assumptions' => 'beliefs_fragile_assumptions',
        'beliefs_invalidated_optional' => 'beliefs_invalidated_optional',
        'round_instruction' => 'round_instruction',
        'interaction_contract' => 'interaction_contract_user',
        'response_format' => 'response_format_weighted',
        'forced_disagreement' => 'forced_disagreement',
        'final_vote' => 'final_vote_instruction',
        'synthesizer_constraints' => 'synthesizer_reliability_envelope',
        'synthesizer_output_format' => 'synthesizer_output_format',
        'chat_user_payload' => 'chat_user_payload',
        'reactive_user_payload' => 'reactive_user_payload',
        'quick_decision_user_payload' => 'quick_decision_user_payload',
        'stress_test_user_payload' => 'stress_test_user_payload',
        'jury_user_payload' => 'jury_user_payload',
        'confrontation_user_payload' => 'confrontation_user_payload',
        'confrontation_synthesis_payload' => 'confrontation_synthesis_payload',
    ];

    /** Suffixe de trace pour segment identique déjà injecté (voir PromptInjectionTraceCollector::isDuplicateSegment). */
    private const TRACE_DEDUP_OMITTED_SUFFIX = '_dedup_omitted';

    /**
     * Normalise un block_id de trace vers la clé registre (ex. beliefs_prioritized_dedup_omitted → beliefs_prioritized).
     */
    public static function canonicalTraceBlockId(string $blockId): string
    {
        $suf = self::TRACE_DEDUP_OMITTED_SUFFIX;
        if (str_ends_with($blockId, $suf)) {
            return substr($blockId, 0, -strlen($suf));
        }

        return $blockId;
    }

    /**
     * @return list<InjectionDef>
     */
    public static function definitions(): array
    {
        $o = 0;
        $def = static function (array $row) use (&$o): array {
            $row['injection_order'] = ++$o;

            return $row;
        };

        return [
            $def([
                'injection_key' => 'global_system',
                'label' => 'Politique globale (global-system.md)',
                'category' => 'policy',
                'priority' => 100,
                'max_chars' => null,
                'soft_budget' => null,
                'hard_budget' => null,
                'context_scope' => 'session',
                'cognitive_layer' => 'governance_layer',
                'provenance_required' => false,
                'deterministic' => true,
                'optional' => false,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => null,
                'pruning_priority' => 10,
                'source_types' => ['markdown_file'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'system',
                'trace_block_id' => null,
            ]),
            $def([
                'injection_key' => 'persona',
                'label' => 'Persona (rôle, style)',
                'category' => 'agent_identity',
                'priority' => 95,
                'max_chars' => null,
                'soft_budget' => 12000,
                'hard_budget' => 24000,
                'context_scope' => 'session',
                'cognitive_layer' => 'agent_identity',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => false,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => 'persona_body',
                'pruning_priority' => 20,
                'source_types' => ['persona_md'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'system',
                'trace_block_id' => null,
            ]),
            $def([
                'injection_key' => 'soul',
                'label' => 'Soul (modificateur comportemental)',
                'category' => 'agent_identity',
                'priority' => 90,
                'max_chars' => null,
                'soft_budget' => 8000,
                'hard_budget' => 16000,
                'context_scope' => 'session',
                'cognitive_layer' => 'agent_identity',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => 'soul_body',
                'pruning_priority' => 25,
                'source_types' => ['soul_md'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'system',
                'trace_block_id' => null,
            ]),
            $def([
                'injection_key' => 'evidence_discipline',
                'label' => 'Evidence discipline block',
                'category' => 'discipline',
                'priority' => 85,
                'max_chars' => null,
                'soft_budget' => null,
                'hard_budget' => null,
                'context_scope' => 'session',
                'cognitive_layer' => 'governance_layer',
                'provenance_required' => false,
                'deterministic' => true,
                'optional' => false,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => null,
                'pruning_priority' => 30,
                'source_types' => ['prompt_builder'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'system',
                'trace_block_id' => null,
            ]),
            $def([
                'injection_key' => 'argument_discipline',
                'label' => 'Argument discipline block',
                'category' => 'discipline',
                'priority' => 84,
                'max_chars' => null,
                'soft_budget' => null,
                'hard_budget' => null,
                'context_scope' => 'session',
                'cognitive_layer' => 'governance_layer',
                'provenance_required' => false,
                'deterministic' => true,
                'optional' => false,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => null,
                'pruning_priority' => 31,
                'source_types' => ['prompt_builder'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'system',
                'trace_block_id' => null,
            ]),
            $def([
                'injection_key' => 'playbook_discipline',
                'label' => 'Playbook discipline (mode)',
                'category' => 'discipline',
                'priority' => 80,
                'max_chars' => null,
                'soft_budget' => null,
                'hard_budget' => null,
                'context_scope' => 'session',
                'cognitive_layer' => 'playbook_runtime',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => false,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => null,
                'pruning_priority' => 32,
                'source_types' => ['playbook_md'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'system',
                'trace_block_id' => null,
            ]),
            $def([
                'injection_key' => 'interaction_contract_system',
                'label' => 'Interaction contract (system)',
                'category' => 'orchestration',
                'priority' => 75,
                'max_chars' => null,
                'soft_budget' => null,
                'hard_budget' => null,
                'context_scope' => 'session',
                'cognitive_layer' => 'orchestration',
                'provenance_required' => false,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => null,
                'pruning_priority' => 40,
                'source_types' => ['prompt_builder'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'system',
                'trace_block_id' => null,
            ]),
            $def([
                'injection_key' => 'decision_dynamics',
                'label' => 'Decision dynamics',
                'category' => 'agent_behavior',
                'priority' => 70,
                'max_chars' => null,
                'soft_budget' => null,
                'hard_budget' => null,
                'context_scope' => 'session',
                'cognitive_layer' => 'agent_behavior',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => null,
                'pruning_priority' => 45,
                'source_types' => ['session_preset', 'persona_db'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'system',
                'trace_block_id' => null,
            ]),
            $def([
                'injection_key' => 'social_dynamics_system',
                'label' => 'Social dynamics (résumé system si présent)',
                'category' => 'social_runtime',
                'priority' => 65,
                'max_chars' => null,
                'soft_budget' => 4000,
                'hard_budget' => 8000,
                'context_scope' => 'strategic_context',
                'cognitive_layer' => 'social_runtime',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => null,
                'pruning_priority' => 50,
                'source_types' => ['social_dynamics_service'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'system',
                'trace_block_id' => null,
            ]),
            $def([
                'injection_key' => 'context_document_system',
                'label' => 'Context document (system path, tronqué)',
                'category' => 'context_document',
                'priority' => 60,
                'max_chars' => 32000,
                'soft_budget' => 28000,
                'hard_budget' => 32000,
                'context_scope' => 'session',
                'cognitive_layer' => 'context_layer',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => true,
                'deduplication_key' => 'context_doc_system',
                'pruning_priority' => 5,
                'source_types' => ['context_document', 'fts_chunks'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'system',
                'trace_block_id' => null,
            ]),
            $def([
                'injection_key' => 'decision_memory_system',
                'label' => 'Decision memory (system injection)',
                'category' => 'decision_memory',
                'priority' => 55,
                'max_chars' => 6000,
                'soft_budget' => 5000,
                'hard_budget' => 6000,
                'context_scope' => 'session',
                'cognitive_layer' => 'decision_memory',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => 'decision_memory_system_block',
                'pruning_priority' => 15,
                'source_types' => ['decision_memories'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'system',
                'trace_block_id' => null,
            ]),
            $def([
                'injection_key' => 'repetition_reduction_system',
                'label' => 'Repetition reduction (system / chat)',
                'category' => 'discipline',
                'priority' => 50,
                'max_chars' => null,
                'soft_budget' => null,
                'hard_budget' => null,
                'context_scope' => 'session',
                'cognitive_layer' => 'governance_layer',
                'provenance_required' => false,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => null,
                'pruning_priority' => 60,
                'source_types' => ['prompt_builder'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'system',
                'trace_block_id' => null,
            ]),
            // ——— User message Decision Room (tracés) ———
            $def([
                'injection_key' => 'context_document',
                'label' => 'Context document (user message)',
                'category' => 'context_document',
                'priority' => 100,
                'max_chars' => 32000,
                'soft_budget' => 28000,
                'hard_budget' => 32000,
                'context_scope' => 'session',
                'cognitive_layer' => 'context_layer',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => true,
                'deduplication_key' => 'context_doc_user_message',
                'pruning_priority' => 5,
                'source_types' => ['context_document', 'fts_chunks'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'context_document',
            ]),
            $def([
                'injection_key' => 'session_objective',
                'label' => 'Objectif de session',
                'category' => 'task',
                'priority' => 99,
                'max_chars' => 8000,
                'soft_budget' => null,
                'hard_budget' => 12000,
                'context_scope' => 'session',
                'cognitive_layer' => 'task',
                'provenance_required' => false,
                'deterministic' => true,
                'optional' => false,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => 'session_objective_text',
                'pruning_priority' => 100,
                'source_types' => ['session'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'objective',
            ]),
            $def([
                'injection_key' => 'strategic_context_guidance',
                'label' => 'Contexte stratégique actif (description workspace)',
                'category' => 'strategic_context',
                'priority' => 98,
                'max_chars' => 24000,
                'soft_budget' => 14000,
                'hard_budget' => 26000,
                'context_scope' => 'strategic_context',
                'cognitive_layer' => 'strategic_context',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => true,
                'deduplication_key' => 'strategic_context_workspace_description',
                'pruning_priority' => 42,
                'source_types' => ['strategic_context', 'workspace'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'strategic_context_guidance',
            ]),
            $def([
                'injection_key' => 'playbook_block',
                'label' => 'Bloc playbook résolu',
                'category' => 'playbook_runtime',
                'priority' => 90,
                'max_chars' => null,
                'soft_budget' => null,
                'hard_budget' => null,
                'context_scope' => 'session',
                'cognitive_layer' => 'playbook_runtime',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => false,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => 'playbook_resolved_block',
                'pruning_priority' => 35,
                'source_types' => ['playbook_runtime'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'playbook_block',
            ]),
            $def([
                'injection_key' => 'playbook_debate_discipline',
                'label' => 'Discipline débat (playbook)',
                'category' => 'discipline',
                'priority' => 88,
                'max_chars' => null,
                'soft_budget' => null,
                'hard_budget' => null,
                'context_scope' => 'session',
                'cognitive_layer' => 'governance_layer',
                'provenance_required' => false,
                'deterministic' => true,
                'optional' => false,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => null,
                'pruning_priority' => 36,
                'source_types' => ['playbook_md'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'debate_discipline',
            ]),
            $def([
                'injection_key' => 'session_history_rounds',
                'label' => 'Historique des tours précédents',
                'category' => 'debate_transcript',
                'priority' => 82,
                'max_chars' => null,
                'soft_budget' => 16000,
                'hard_budget' => 48000,
                'context_scope' => 'session',
                'cognitive_layer' => 'debate_transcript',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => 'previous_rounds_blob',
                'pruning_priority' => 12,
                'source_types' => ['messages'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'previous_rounds',
            ]),
            $def([
                'injection_key' => 'debate_argument_memory',
                'label' => 'Argument memory (résumé débat)',
                'category' => 'debate_memory',
                'priority' => 78,
                'max_chars' => null,
                'soft_budget' => 8000,
                'hard_budget' => 20000,
                'context_scope' => 'session',
                'cognitive_layer' => 'debate_memory',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => 'debate_argument_memory_summary',
                'pruning_priority' => 18,
                'source_types' => ['debate_memory_service'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'argument_memory',
            ]),
            $def([
                'injection_key' => 'social_dynamics_policy',
                'label' => 'Politique social-dynamics (fichier)',
                'category' => 'social_governance',
                'priority' => 72,
                'max_chars' => null,
                'soft_budget' => null,
                'hard_budget' => null,
                'context_scope' => 'session',
                'cognitive_layer' => 'social_governance',
                'provenance_required' => false,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => 'social_policy_markdown',
                'pruning_priority' => 55,
                'source_types' => ['markdown_file'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'social_policy',
            ]),
            $def([
                'injection_key' => 'social_dynamics_context',
                'label' => 'Bloc social runtime (majorité / relations)',
                'category' => 'social_runtime',
                'priority' => 71,
                'max_chars' => null,
                'soft_budget' => 6000,
                'hard_budget' => 12000,
                'context_scope' => 'strategic_context',
                'cognitive_layer' => 'social_runtime',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => 'social_user_block',
                'pruning_priority' => 52,
                'source_types' => ['social_prompt_context_builder'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'social_dynamics_block',
            ]),
            $def([
                'injection_key' => 'agent_context_memory',
                'label' => 'Mémoire agent située (memory.md)',
                'category' => 'situated_memory',
                'priority' => 68,
                'max_chars' => null,
                'soft_budget' => 6000,
                'hard_budget' => 12000,
                'context_scope' => 'strategic_context',
                'cognitive_layer' => 'situated_memory',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => 'agent_context_memory_prompt_block',
                'pruning_priority' => 22,
                'source_types' => ['agent_memory_md'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'agent_context_memory',
            ]),
            $def([
                'injection_key' => 'beliefs_prioritized',
                'label' => 'Beliefs prioritaires (runtime, déterministe)',
                'category' => 'beliefs',
                'priority' => 69,
                'max_chars' => null,
                'soft_budget' => 3000,
                'hard_budget' => 7000,
                'context_scope' => 'strategic_context',
                'cognitive_layer' => 'beliefs',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => 'beliefs_prioritized_digest',
                'pruning_priority' => 19,
                'source_types' => ['strategic_context_beliefs'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'beliefs_prioritized',
            ]),
            $def([
                'injection_key' => 'beliefs_contested',
                'label' => 'Beliefs contestés (runtime)',
                'category' => 'beliefs',
                'priority' => 67,
                'max_chars' => null,
                'soft_budget' => 2400,
                'hard_budget' => 5200,
                'context_scope' => 'strategic_context',
                'cognitive_layer' => 'beliefs',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => 'beliefs_contested_digest',
                'pruning_priority' => 21,
                'source_types' => ['strategic_context_beliefs'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'beliefs_contested',
            ]),
            $def([
                'injection_key' => 'beliefs_fragile_assumptions',
                'label' => 'Hypothèses fragiles (runtime)',
                'category' => 'beliefs',
                'priority' => 66,
                'max_chars' => null,
                'soft_budget' => 1800,
                'hard_budget' => 4200,
                'context_scope' => 'strategic_context',
                'cognitive_layer' => 'beliefs',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => 'beliefs_fragile_digest',
                'pruning_priority' => 23,
                'source_types' => ['strategic_context_beliefs'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'beliefs_fragile_assumptions',
            ]),
            $def([
                'injection_key' => 'beliefs_invalidated_optional',
                'label' => 'Beliefs invalidés (optionnel, expert)',
                'category' => 'beliefs',
                'priority' => 30,
                'max_chars' => null,
                'soft_budget' => 1200,
                'hard_budget' => 3000,
                'context_scope' => 'strategic_context',
                'cognitive_layer' => 'beliefs',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => 'beliefs_invalidated_digest',
                'pruning_priority' => 24,
                'source_types' => ['strategic_context_beliefs'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'beliefs_invalidated_optional',
            ]),
            $def([
                'injection_key' => 'strategic_narrative_echo',
                'label' => 'Strategic narrative (echo dérivé, non canonique)',
                'category' => 'derived_narrative',
                'priority' => 40,
                'max_chars' => null,
                'soft_budget' => 4000,
                'hard_budget' => 8000,
                'context_scope' => 'strategic_context',
                'cognitive_layer' => 'derived_narrative',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => true,
                'retrieval_allowed' => false,
                'deduplication_key' => 'strategic_narrative_injected_body',
                'pruning_priority' => 8,
                'source_types' => ['strategic_narrative_service'],
                'supports_cross_context' => false,
                'enabled_by_default' => false,
                'channel' => 'either',
                'trace_block_id' => null,
            ]),
            $def([
                'injection_key' => 'beliefs_echo',
                'label' => 'Beliefs (echo contrôlé, non canonique vs faits)',
                'category' => 'beliefs',
                'priority' => 38,
                'max_chars' => null,
                'soft_budget' => 4000,
                'hard_budget' => 12000,
                'context_scope' => 'strategic_context',
                'cognitive_layer' => 'beliefs',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => true,
                'retrieval_allowed' => false,
                'deduplication_key' => 'beliefs_injected_digest',
                'pruning_priority' => 9,
                'source_types' => ['strategic_context_beliefs'],
                'supports_cross_context' => false,
                'enabled_by_default' => false,
                'channel' => 'either',
                'trace_block_id' => null,
            ]),
            $def([
                'injection_key' => 'compiled_memory_echo',
                'label' => 'Memory compilation (echo, dérivé)',
                'category' => 'compiled_memory',
                'priority' => 36,
                'max_chars' => null,
                'soft_budget' => 6000,
                'hard_budget' => 14000,
                'context_scope' => 'strategic_context',
                'cognitive_layer' => 'compiled_memory',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => true,
                'retrieval_allowed' => false,
                'deduplication_key' => 'compiled_memory_digest',
                'pruning_priority' => 11,
                'source_types' => ['memory_compilations'],
                'supports_cross_context' => false,
                'enabled_by_default' => false,
                'channel' => 'either',
                'trace_block_id' => null,
            ]),
            $def([
                'injection_key' => 'context_snapshot_echo',
                'label' => 'Snapshot contexte (echo figé, non vivant)',
                'category' => 'snapshot',
                'priority' => 34,
                'max_chars' => null,
                'soft_budget' => 4000,
                'hard_budget' => 10000,
                'context_scope' => 'strategic_context',
                'cognitive_layer' => 'snapshot',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => true,
                'retrieval_allowed' => false,
                'deduplication_key' => 'snapshot_echo_digest',
                'pruning_priority' => 7,
                'source_types' => ['strategic_context_snapshots'],
                'supports_cross_context' => false,
                'enabled_by_default' => false,
                'channel' => 'either',
                'trace_block_id' => null,
            ]),
            $def([
                'injection_key' => 'workspace_timeline_snippet',
                'label' => 'Snippet timeline workspace',
                'category' => 'timeline',
                'priority' => 32,
                'max_chars' => null,
                'soft_budget' => 4000,
                'hard_budget' => 8000,
                'context_scope' => 'strategic_context',
                'cognitive_layer' => 'timeline',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => true,
                'retrieval_allowed' => false,
                'deduplication_key' => 'timeline_snippet',
                'pruning_priority' => 14,
                'source_types' => ['workspace_timeline'],
                'supports_cross_context' => false,
                'enabled_by_default' => false,
                'channel' => 'either',
                'trace_block_id' => null,
            ]),
            $def([
                'injection_key' => 'evidence_report_echo',
                'label' => 'Evidence report (extrait)',
                'category' => 'evidence',
                'priority' => 30,
                'max_chars' => null,
                'soft_budget' => 4000,
                'hard_budget' => 10000,
                'context_scope' => 'session',
                'cognitive_layer' => 'evidence',
                'provenance_required' => true,
                'deterministic' => false,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => 'evidence_report_digest',
                'pruning_priority' => 16,
                'source_types' => ['evidence_reports'],
                'supports_cross_context' => false,
                'enabled_by_default' => false,
                'channel' => 'either',
                'trace_block_id' => null,
            ]),
            $def([
                'injection_key' => 'risk_profile_echo',
                'label' => 'Risk profile (extrait)',
                'category' => 'risk',
                'priority' => 28,
                'max_chars' => null,
                'soft_budget' => 3000,
                'hard_budget' => 8000,
                'context_scope' => 'session',
                'cognitive_layer' => 'risk',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => 'risk_profile_digest',
                'pruning_priority' => 17,
                'source_types' => ['session_risk_profiles'],
                'supports_cross_context' => false,
                'enabled_by_default' => false,
                'channel' => 'either',
                'trace_block_id' => null,
            ]),
            $def([
                'injection_key' => 'round_instruction',
                'label' => 'Instruction de tour (RoundPolicy)',
                'category' => 'orchestration',
                'priority' => 64,
                'max_chars' => null,
                'soft_budget' => null,
                'hard_budget' => null,
                'context_scope' => 'session',
                'cognitive_layer' => 'orchestration',
                'provenance_required' => false,
                'deterministic' => true,
                'optional' => false,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => null,
                'pruning_priority' => 90,
                'source_types' => ['round_policy'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'round_instruction',
            ]),
            $def([
                'injection_key' => 'interaction_contract_user',
                'label' => 'Interaction contract + ciblage (user)',
                'category' => 'orchestration',
                'priority' => 62,
                'max_chars' => null,
                'soft_budget' => null,
                'hard_budget' => null,
                'context_scope' => 'session',
                'cognitive_layer' => 'orchestration',
                'provenance_required' => false,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => null,
                'pruning_priority' => 88,
                'source_types' => ['prompt_builder'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'interaction_contract',
            ]),
            $def([
                'injection_key' => 'response_format_weighted',
                'label' => 'Format de réponse + opinion pondérée',
                'category' => 'instruction',
                'priority' => 58,
                'max_chars' => null,
                'soft_budget' => null,
                'hard_budget' => null,
                'context_scope' => 'session',
                'cognitive_layer' => 'instruction',
                'provenance_required' => false,
                'deterministic' => true,
                'optional' => false,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => null,
                'pruning_priority' => 92,
                'source_types' => ['prompt_builder'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'response_format',
            ]),
            $def([
                'injection_key' => 'forced_disagreement',
                'label' => 'Instruction forced disagreement',
                'category' => 'governance_layer',
                'priority' => 56,
                'max_chars' => null,
                'soft_budget' => null,
                'hard_budget' => null,
                'context_scope' => 'session',
                'cognitive_layer' => 'governance_layer',
                'provenance_required' => false,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => null,
                'pruning_priority' => 93,
                'source_types' => ['session_option'],
                'supports_cross_context' => false,
                'enabled_by_default' => false,
                'channel' => 'user',
                'trace_block_id' => 'forced_disagreement',
            ]),
            $def([
                'injection_key' => 'final_vote_instruction',
                'label' => 'Schéma vote final',
                'category' => 'vote',
                'priority' => 54,
                'max_chars' => null,
                'soft_budget' => null,
                'hard_budget' => null,
                'context_scope' => 'session',
                'cognitive_layer' => 'vote',
                'provenance_required' => false,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => null,
                'pruning_priority' => 94,
                'source_types' => ['prompt_builder'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'final_vote',
            ]),
            $def([
                'injection_key' => 'synthesizer_reliability_envelope',
                'label' => 'Contraintes synthétiseur (fiabilité)',
                'category' => 'reliability_envelope',
                'priority' => 52,
                'max_chars' => null,
                'soft_budget' => 12000,
                'hard_budget' => 24000,
                'context_scope' => 'session',
                'cognitive_layer' => 'reliability_envelope',
                'provenance_required' => true,
                'deterministic' => false,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => 'synthesizer_constraints_blob',
                'pruning_priority' => 3,
                'source_types' => ['votes', 'evidence', 'guardrails'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'synthesizer_constraints',
            ]),
            $def([
                'injection_key' => 'synthesizer_output_format',
                'label' => 'Format sortie synthétiseur',
                'category' => 'instruction',
                'priority' => 51,
                'max_chars' => null,
                'soft_budget' => null,
                'hard_budget' => null,
                'context_scope' => 'session',
                'cognitive_layer' => 'instruction',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => false,
                'retrieval_allowed' => false,
                'deduplication_key' => null,
                'pruning_priority' => 4,
                'source_types' => ['playbook_runtime'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'synthesizer_output_format',
            ]),
            $def([
                'injection_key' => 'chat_user_payload',
                'label' => 'Payload utilisateur chat global',
                'category' => 'orchestration',
                'priority' => 46,
                'max_chars' => 32000,
                'soft_budget' => 18000,
                'hard_budget' => 32000,
                'context_scope' => 'session',
                'cognitive_layer' => 'orchestration',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => false,
                'requires_expert_mode' => false,
                'retrieval_allowed' => true,
                'deduplication_key' => 'chat_user_payload_dedup',
                'pruning_priority' => 26,
                'source_types' => ['prompt_builder'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'chat_user_payload',
            ]),
            $def([
                'injection_key' => 'reactive_user_payload',
                'label' => 'Payload utilisateur chat reactif',
                'category' => 'orchestration',
                'priority' => 46,
                'max_chars' => 36000,
                'soft_budget' => 22000,
                'hard_budget' => 36000,
                'context_scope' => 'session',
                'cognitive_layer' => 'orchestration',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => false,
                'requires_expert_mode' => false,
                'retrieval_allowed' => true,
                'deduplication_key' => 'reactive_user_payload_dedup',
                'pruning_priority' => 26,
                'source_types' => ['prompt_builder', 'runner_inline'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'reactive_user_payload',
            ]),
            $def([
                'injection_key' => 'quick_decision_user_payload',
                'label' => 'Payload utilisateur quick decision',
                'category' => 'orchestration',
                'priority' => 47,
                'max_chars' => 40000,
                'soft_budget' => 24000,
                'hard_budget' => 40000,
                'context_scope' => 'session',
                'cognitive_layer' => 'orchestration',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => false,
                'requires_expert_mode' => false,
                'retrieval_allowed' => true,
                'deduplication_key' => 'quick_decision_user_payload_dedup',
                'pruning_priority' => 25,
                'source_types' => ['prompt_builder'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'quick_decision_user_payload',
            ]),
            $def([
                'injection_key' => 'stress_test_user_payload',
                'label' => 'Payload utilisateur stress test',
                'category' => 'orchestration',
                'priority' => 47,
                'max_chars' => 48000,
                'soft_budget' => 28000,
                'hard_budget' => 48000,
                'context_scope' => 'session',
                'cognitive_layer' => 'orchestration',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => false,
                'requires_expert_mode' => false,
                'retrieval_allowed' => true,
                'deduplication_key' => 'stress_test_user_payload_dedup',
                'pruning_priority' => 25,
                'source_types' => ['prompt_builder'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'stress_test_user_payload',
            ]),
            $def([
                'injection_key' => 'jury_user_payload',
                'label' => 'Payload utilisateur jury',
                'category' => 'orchestration',
                'priority' => 47,
                'max_chars' => 52000,
                'soft_budget' => 30000,
                'hard_budget' => 52000,
                'context_scope' => 'session',
                'cognitive_layer' => 'orchestration',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => false,
                'requires_expert_mode' => false,
                'retrieval_allowed' => true,
                'deduplication_key' => 'jury_user_payload_dedup',
                'pruning_priority' => 25,
                'source_types' => ['prompt_builder', 'runner_inline'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'jury_user_payload',
            ]),
            $def([
                'injection_key' => 'confrontation_user_payload',
                'label' => 'Payload utilisateur confrontation',
                'category' => 'orchestration',
                'priority' => 47,
                'max_chars' => 48000,
                'soft_budget' => 28000,
                'hard_budget' => 48000,
                'context_scope' => 'session',
                'cognitive_layer' => 'orchestration',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => false,
                'requires_expert_mode' => false,
                'retrieval_allowed' => true,
                'deduplication_key' => 'confrontation_user_payload_dedup',
                'pruning_priority' => 25,
                'source_types' => ['prompt_builder'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'confrontation_user_payload',
            ]),
            $def([
                'injection_key' => 'confrontation_synthesis_payload',
                'label' => 'Payload synthese confrontation',
                'category' => 'orchestration',
                'priority' => 47,
                'max_chars' => 52000,
                'soft_budget' => 32000,
                'hard_budget' => 52000,
                'context_scope' => 'session',
                'cognitive_layer' => 'orchestration',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => false,
                'requires_expert_mode' => false,
                'retrieval_allowed' => true,
                'deduplication_key' => 'confrontation_synthesis_payload_dedup',
                'pruning_priority' => 25,
                'source_types' => ['prompt_builder', 'runner_inline'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'user',
                'trace_block_id' => 'confrontation_synthesis_payload',
            ]),
            $def([
                'injection_key' => 'situated_chat_context',
                'label' => 'Contexte chat situé (résumé + blocs optionnels)',
                'category' => 'situated_chat',
                'priority' => 45,
                'max_chars' => null,
                'soft_budget' => 12000,
                'hard_budget' => 24000,
                'context_scope' => 'strategic_context',
                'cognitive_layer' => 'situated_chat',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => false,
                'requires_expert_mode' => false,
                'retrieval_allowed' => true,
                'deduplication_key' => 'situated_chat_assembled',
                'pruning_priority' => 20,
                'source_types' => ['strategic_context', 'agent_memory', 'social', 'decisions'],
                'supports_cross_context' => false,
                'enabled_by_default' => true,
                'channel' => 'either',
                'trace_block_id' => null,
            ]),
            $def([
                'injection_key' => 'replay_builder_context',
                'label' => 'Replay / reconstitution historique',
                'category' => 'replay',
                'priority' => 20,
                'max_chars' => null,
                'soft_budget' => 16000,
                'hard_budget' => 32000,
                'context_scope' => 'session',
                'cognitive_layer' => 'replay',
                'provenance_required' => true,
                'deterministic' => true,
                'optional' => true,
                'requires_expert_mode' => true,
                'retrieval_allowed' => false,
                'deduplication_key' => 'replay_digest',
                'pruning_priority' => 13,
                'source_types' => ['messages', 'votes'],
                'supports_cross_context' => false,
                'enabled_by_default' => false,
                'channel' => 'either',
                'trace_block_id' => null,
            ]),
        ];
    }

    /**
     * @return array<string, InjectionDef>
     */
    public static function definitionsByKey(): array
    {
        $map = [];
        foreach (self::definitions() as $row) {
            $map[$row['injection_key']] = $row;
        }

        return $map;
    }

    /** @return array<string, mixed>|null */
    public static function definitionForBlockId(string $blockId): ?array
    {
        $canonical = self::canonicalTraceBlockId($blockId);
        $key = self::BLOCK_ID_TO_INJECTION_KEY[$canonical] ?? null;
        if ($key === null) {
            return null;
        }
        $by = self::definitionsByKey();

        return $by[$key] ?? null;
    }

    public static function injectionKeyForBlockId(string $blockId): string
    {
        $canonical = self::canonicalTraceBlockId($blockId);

        return self::BLOCK_ID_TO_INJECTION_KEY[$canonical] ?? $canonical;
    }

    public static function deduplicationKeyForBlockId(string $blockId): ?string
    {
        $def = self::definitionForBlockId($blockId);
        if ($def === null) {
            return null;
        }
        $k = $def['deduplication_key'] ?? null;

        return is_string($k) && $k !== '' ? $k : null;
    }

    /** @return array<string, mixed> */
    public static function traceFieldsFromDefinition(array $def): array
    {
        return [
            'injection_key' => $def['injection_key'],
            'registry_label' => $def['label'],
            'category' => $def['category'],
            'priority' => $def['priority'],
            'injection_order' => $def['injection_order'],
            'max_chars' => $def['max_chars'],
            'soft_budget' => $def['soft_budget'],
            'hard_budget' => $def['hard_budget'],
            'context_scope' => $def['context_scope'],
            'registry_cognitive_layer' => $def['cognitive_layer'],
            'provenance_required' => $def['provenance_required'],
            'deterministic' => $def['deterministic'],
            'optional' => $def['optional'],
            'requires_expert_mode' => $def['requires_expert_mode'],
            'retrieval_allowed' => $def['retrieval_allowed'],
            'deduplication_key' => $def['deduplication_key'],
            'pruning_priority' => $def['pruning_priority'],
            'supports_cross_context' => $def['supports_cross_context'],
            'enabled_by_default' => $def['enabled_by_default'],
        ];
    }

    /** Bundle pour Cognitive Governance API + UI expert. */
    public static function governanceExport(): array
    {
        return [
            'schema_version' => self::SCHEMA_VERSION,
            'definitions' => self::definitions(),
            'official_order_system' => self::OFFICIAL_ORDER_SYSTEM,
            'official_order_decision_room_user' => self::OFFICIAL_ORDER_DECISION_ROOM_USER,
            'block_id_to_injection_key' => self::BLOCK_ID_TO_INJECTION_KEY,
            'notes' => [
                'Les entrées enabled_by_default=false sont réservées aux futurs chemins explicites (narrative/beliefs/…) et ne doivent pas être injectées sans politique runtime.',
                'Les budgets soft/hard sont indicatifs pour gouvernance ; la troncature effective reste dans les implémentations (ex. MAX_CONTEXT_INJECT_CHARS).',
            ],
        ];
    }
}
