const createInitialState = () => ({
  view: 'dashboard',
  sessions: [],
  personas: [],
  providers: [],
  providerRoutingSettings: null,
  providerRoutingSaveStatus: null,
  providerRoutingSaveMessage: '',
  logs: {
    items: null,
    loading: false,
    error: null,
    selectedId: null,
    selected: null,
    filters: {
      level: '',
      category: '',
      session_id: '',
      provider_id: '',
      agent_id: '',
      from: '',
      to: '',
      search: '',
      limit: 100,
      offset: 0,
    },
    exportStatus: null,
    maintenanceStatus: null,
  },
  providerModelOptions: [],
  providerModelStatus: null,
  providerModelError: '',
  souls: [],
  currentSession: null,
  currentMessages: [],
  followUpMessages: [],
  followUpLoading: false,
  isLoading: false,
  drResults: null,
  drRunning: false,
  confrontationResults: null,
  confrontationRunning: false,
  reactiveChat: {
    enabled:                      false,
    primaryAgentId:               '',
    reactorAgentIds:              [],
    turnsMin:                     2,
    turnsMax:                     4,
    earlyStopEnabled:             true,
    earlyStopConfidenceThreshold: 0.85,
    noNewArgumentsThreshold:      2,
    reactorMode:                  'independent',
    debateIntensity:              'medium',
    reactionStyle:                'critical',
    includeFinalSynthesis:        true,
    running:                      false,
    error:                        null,
  },
  reactiveChatResults: null,
  snapshotStatus: null,
  error: null,
  /** "simple" | "expert" — progressive disclosure (legacy) */
  uiMode: 'simple',
  /** "basic" | "advanced" | "expert" — persisted in localStorage */
  uiComplexity: (() => {
    try { return localStorage.getItem('da_ui_complexity') || 'advanced'; } catch (_) { return 'advanced'; }
  })(),
  /** Set of panel keys currently collapsed in session history */
  collapsedPanels: (() => {
    try {
      const saved = localStorage.getItem('da_collapsed_panels');
      return saved ? new Set(JSON.parse(saved)) : new Set(['social-dynamics', 'bias-detection', 'llm-used', 'evidence', 'risk', 'persona-scores']);
    } catch (_) { return new Set(); }
  })(),
  sessionHistory: null,
  newSession: {
    title: '',
    idea: '',
    mode: 'chat',
    selectedAgents: [],
    rounds: 3,
    language: 'fr',
    blueTeam: ['pm', 'architect', 'po', 'ux-expert'],
    redTeam: ['analyst', 'critic'],
    includeSynthesis: true,
    cfRounds: 3,
    cfStyle: 'sequential',
    cfReplyPolicy: 'all-agents-reply',
    forceDisagreement: false,
    juryThreshold: 0.55,
    selectedScenarioId: null,
    ctxDocEnabled: false,
    ctxDocTab: 'manual',
    ctxDocTitle: '',
    ctxDocContent: '',
    ctxDocDraftSaved: false,
    ctxDocDraftSummary: null,
  },
  currentContextDoc: null,
  ctxDocPanelOpen: false,
  personaMaker: {
    description: '',
    providerId: '',
    model: '',
    isGenerating: false,
    result: null,
    error: null,
    previewTab: 'persona',
    saveStatus: null,
    saveMessage: '',
    overwrite: false,
  },
  personaBuilder: {
    id: '',
    name: '',
    title: '',
    icon: '🤖',
    tags: '',
    defaultProvider: '',
    defaultModel: '',
    enabled: true,
    role: '',
    whenToUse: '',
    style: '',
    identity: '',
    focus: '',
    corePrinciples: '',
    capabilities: '',
    constraints: '',
    defaultResponseFormat: '',
    systemInstructions: '',
    personality: '',
    behavioralRules: '',
    reasoningStyle: '',
    communicationStyle: '',
    defaultBias: '',
    challengeLevel: 'medium',
    outputPreferences: '',
    guardrails: '',
    description: '',
    isGenerating: false,
    previewTab: 'persona',
    saveStatus: null,
    saveMessage: '',
    generationError: null,
    overwrite: false,
  },
  sessionFilter: 'all',
  templates: [],
  scenarioPacks: [],
  qdResults: null,
  qdRunning: false,
  stResults: null,
  stRunning: false,
  chatAbortController: null,
  graphData: null,
  graphLoading: false,
  graphError: null,
  heatmapData: null,
  heatmapLoading: false,
  heatmapError: null,
  heatmapFilter: 'all',
  replayEvents: null,
  replayLoading: false,
  replayError: null,
  replayIndex: 0,
  replayPlaying: false,
  replaySpeed: 1,
  auditData: null,
  auditLoading: false,
  auditError: null,
  voteExplanation: null,
  voteExplanationLoading: false,
  voteExplanationError: null,
  lastRecomputeThreshold: null, // { sessionId: string, threshold: number } | null
  actionPlan: null,
  actionPlanLoading: false,
  actionPlanStatus: null,
  comparisons: [],
  currentComparison: null,
  comparisonLoading: false,
  compareSelectedIds: [],
  rerunModal: {
    open: false,
    sessionId: null,
    variations: [],
    targetMode: '',
    language: '',
    customInstruction: '',
    keepContext: true,
    loading: false,
  },
  launchAssistant: {
    step: 1,
    intent: null,
    description: '',
    recommendation: null,
    loading: false,
    editMode: null,
    editRounds: 2,
    editAgents: [],
    editForceDisagreement: true,
    editMode2: '',
  },
  templateMaker: {
    description: '',
    providerId: '',
    model: '',
    isGenerating: false,
    result: null,
    error: null,
    saveStatus: null,
    saveMessage: '',
  },
  postmortemStats: null,
  postmortemStatsLoading: false,
  postmortemStatsError: null,
  templateMakerData: {
    id: '',
    name: '',
    description: '',
    mode: 'decision-room',
    selectedAgents: [],
    rounds: 2,
    forceDisagreement: false,
    interactionStyle: 'sequential',
    replyPolicy: 'all-agents-reply',
    finalSynthesis: true,
    promptStarter: '',
    expectedOutput: '',
    notes: '',
    enabled: true,
    editingId: null,
    saveStatus: null,
    saveMessage: '',
    overwrite: false,
  },
});

const state = createInitialState();

function resetState() {
  const fresh = createInitialState();
  Object.keys(state).forEach((key) => {
    delete state[key];
  });
  Object.assign(state, fresh);
}

function patchState(partial) {
  Object.assign(state, partial);
}

function setView(view) {
  state.view = view;
}

export {
  createInitialState,
  state,
  resetState,
  patchState,
  setView,
};
